package test.selenium.account;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
if(System.getProperty("os.name").startsWith("Mac")) {
	System.setProperty("webdriver.chrome.driver", "chromedriverMac");
} else if(System.getProperty("os.name").startsWith("Windows")) {
	System.setProperty("webdriver.chrome.driver", "chromedriverWin.exe");
}
System.setProperty("webdriver.chrome.driver", "chromedriverMac");
driver = new ChromeDriver();
js = (JavascriptExecutor) driver;
vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
driver.quit();
}
@Test
public void testLogin() {
driver.get("http://localhost/NetPharma/login.jsp");
driver.manage().window().setSize(new Dimension(1194, 802));
driver.findElement(By.id("username")).click();
driver.findElement(By.id("username")).sendKeys("mrossi");
driver.findElement(By.id("password")).click();
driver.findElement(By.id("password")).sendKeys("pw");
driver.findElement(By.cssSelector(".container-accesso > .btn")).click();
assertThat(driver.getTitle(), is("HomePage"));
}
@Test
public void testLoginUsernameNotExisting() {
driver.get("http://localhost/NetPharma/login.jsp");
driver.findElement(By.id("username")).click();
driver.findElement(By.id("username")).sendKeys("ok");
driver.findElement(By.id("password")).click();
driver.findElement(By.id("password")).sendKeys("pw");
driver.findElement(By.cssSelector(".container-accesso > .btn")).click();
{
 List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(1) .invalid-feedback"));
 assert(elements.size() > 0);
}
{
 List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(2) .invalid-feedback"));
 assert(elements.size() > 0);
}
}
@Test
public void testLoginWrongPassword() {
driver.get("http://localhost/NetPharma/login.jsp");
driver.manage().window().setSize(new Dimension(1194, 802));
driver.findElement(By.id("username")).click();
driver.findElement(By.id("username")).sendKeys("mrossi");
driver.findElement(By.id("password")).click();
driver.findElement(By.id("password")).sendKeys("ok");
{
 List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(1) .valid-feedback"));
 assert(elements.size() > 0);
}
{
 List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(2) .invalid-feedback"));
 assert(elements.size() > 0);
}
}
}


