package test.selenium.account;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrazioneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	if(System.getProperty("os.name").startsWith("Mac")) {
		System.setProperty("webdriver.chrome.driver", "chromedriverMac");
	} else if(System.getProperty("os.name").startsWith("Windows")) {
		System.setProperty("webdriver.chrome.driver", "chromedriverWin.exe");
	}
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testRegistrazione() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Marco");
    driver.findElement(By.id("cognome")).sendKeys("Accedi");
    driver.findElement(By.id("username")).sendKeys("maccedi");
    driver.findElement(By.id("email")).sendKeys("maccedi@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-07-16");
    driver.findElement(By.id("nascita")).sendKeys("0019-07-16");
    driver.findElement(By.id("nascita")).sendKeys("0197-07-16");
    driver.findElement(By.id("nascita")).sendKeys("1972-07-16");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!!!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    assertThat(driver.getTitle(), is("HomePage"));
  }
  @Test
  public void testRegistrazioneEmailPresente() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("m@rossi.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-5 > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneEta() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0002-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0020-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0202-12-12");
    driver.findElement(By.id("nascita")).sendKeys("2020-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3 > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneFormatoCognome() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta1");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(2) > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneFormatoEmail() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagentagmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-5 > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneFormatoNome() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni1");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(1) > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneFormatoPassword() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("Password123");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-4 > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneFormatoUsername() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.cssSelector("form:nth-child(2)")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("gmagenta@");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(4) > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneLunghezzaCognome() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Quondammagentamarianico");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
    driver.manage().window().setSize(new Dimension(822, 824));
  }
  @Test
  public void testRegistrazioneLunghezzaEmail() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("giannimagentacommercialistadiudinevianapoli27@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
  }
  @Test
  public void testRegistrazioneLunghezzaNome() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("GianniAntonioMariaFilippo");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
  }
  @Test
  public void testRegistrazioneLunghezzaPassword() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("gmagenta");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("pw");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-4 > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistrazioneLunghezzaUsername() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(826, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("giannimagentacommercialistadiudinevianapoli27");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
  }
  @Test
  public void testRegistrazioneUsernamePresente() {
    driver.get("http://localhost/NetPharma/registrazione.jsp");
    driver.manage().window().setSize(new Dimension(822, 824));
    driver.findElement(By.cssSelector(".custom-control:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Gianni");
    driver.findElement(By.id("cognome")).sendKeys("Magenta");
    driver.findElement(By.id("username")).sendKeys("mrossi");
    driver.findElement(By.id("email")).sendKeys("gmagenta@gmail.com");
    driver.findElement(By.id("nascita")).sendKeys("0001-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0019-12-12");
    driver.findElement(By.id("nascita")).sendKeys("0198-12-12");
    driver.findElement(By.id("nascita")).sendKeys("1980-12-12");
    driver.findElement(By.id("password")).sendKeys("P4ssw0rd!");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(6) > .invalid-feedback"));
      assert(elements.size() > 0);
    }
  }
}
