// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InserimentoProdottoNelCatalogoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC1() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116436");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Erba Vita Aloe Vera Gel Protettivo Idratante 200 ml");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("tubo");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Descrizione Aloe Vera");
    driver.findElement(By.id("descrizione")).sendKeys("Descrizione Aloe Vera Gel Erba Vita");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.id("categoria")).click();
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Successo"));
  }
  @Test
  public void tC2() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116439");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(3) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(3) > .invalid-feedback")).getText(), is("Inserisci un nome (max. 100 caratteri)"));
  }
  @Test
  public void tC3() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("885");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(2) > .invalid-feedback")).getText(), is("Attenzione! Esiste già un prodotto nel catalogo con il codice specificato"));
  }
  @Test
  public void tC4() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116439");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".col-md-8")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(4) > .invalid-feedback")).getText(), is("Inserisci un marchio (max. 50 caratteri)"));
  }
  @Test
  public void tC5() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116437");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector("body")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
  }
  @Test
  public void tC6() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116437");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector("body")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
  }
  @Test
  public void tC7() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116437");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(7) > .invalid-feedback")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(7) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(7) > .invalid-feedback")).getText(), is("Inserisci una descrizione!"));
  }
  @Test
  public void tC8() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116437");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("0");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(9) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(9) > .invalid-feedback")).getText(), is("Il prezzo inserito non è valido!"));
  }
  @Test
  public void tC9() {
    driver.get("http://localhost/NetPharma/gestoreCatalogo/aggiungiProdotto.jsp");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("id")).click();
    driver.findElement(By.id("id")).sendKeys("927116437");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("0");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(8) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(8) > .invalid-feedback")).getText(), is("Disponibilità deve essere un intero positivo!"));
  }
}
