package test.selenium.prodotto;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaProdottoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  if(System.getProperty("os.name").startsWith("Mac")) {
			System.setProperty("webdriver.chrome.driver", "chromedriverMac");
		} else if(System.getProperty("os.name").startsWith("Windows")) {
			System.setProperty("webdriver.chrome.driver", "chromedriverWin.exe");
		}
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC10() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Pampers Salviette Sensitive Aloe 63 Pezzi']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Successo"));
  }
  @Test
  public void tC11() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Chicco Biberon Natural Feeling +2m Boy 250 ml']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys(" ");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(3) > .invalid-feedback")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(3) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(3) > .invalid-feedback")).getText(), is("Inserisci un nome (max. 100 caratteri)"));
  }
  @Test
  public void tC12() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Chicco Biberon Natural Feeling +2m Boy 250 ml']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("marchio")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("marchio")).sendKeys(" ");
    driver.findElement(By.id("produttore")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.id("formato")).click();
    {
      WebElement element = driver.findElement(By.id("formato"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.cssSelector(".col-md-8")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-8"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(4) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(4) > .invalid-feedback")).getText(), is("Inserisci un marchio (max. 50 caratteri)"));
  }
  @Test
  public void tC13() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Chicco Biberon Natural Feeling +2m Boy 250 ml']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
  }
  @Test
  public void tC14() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Chicco Biberon Natural Feeling +2m Boy 250 ml']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.getTitle(), is("NetPharma ‐ Errore"));
  }
  @Test
  public void tC15() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Chicco Biberon Natural Feeling +2m Boy 250 ml']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("descrizione")).sendKeys(" ");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".col-md-8")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(7) > .invalid-feedback")).getText(), is("Inserisci una descrizione!"));
  }
  @Test
  public void tC16() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Chicco Biberon Natural Feeling +2m Boy 250 ml']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.id("formato")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.id("descrizione")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("100");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("prezzo")).sendKeys("0");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(9) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(9) > .invalid-feedback")).getText(), is("Il prezzo inserito non è valido!"));
  }
  @Test
  public void tC17() {
    driver.get("http://localhost/NetPharma/ModificaProdotto");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("prodotto")).click();
    {
      WebElement dropdown = driver.findElement(By.id("prodotto"));
      dropdown.findElement(By.xpath("//option[. = 'Chicco Biberon Natural Feeling +2m Boy 250 ml']")).click();
    }
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("nome")).sendKeys("PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("marchio")).sendKeys("Erba Vita");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("produttore")).sendKeys("Erba Vita group spa");
    driver.findElement(By.cssSelector(".col-md-8")).click();
    driver.findElement(By.id("formato")).sendKeys("bustine, PAPAYA FERMENTATA FQ BUSTINE, Antiossidante naturale");
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("descrizione")).sendKeys("Antiossidante naturale");
    driver.findElement(By.id("disponibilita")).click();
    driver.findElement(By.id("disponibilita")).sendKeys("0");
    driver.findElement(By.id("prezzo")).click();
    driver.findElement(By.id("prezzo")).sendKeys("13.00");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(8) > .invalid-feedback")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(8) > .invalid-feedback")).getText(), is("Disponibilità deve essere un intero positivo!"));
  }
}
